"""empty message

Revision ID: 1c28d4dbb62
Revises: 7847a1b6d3
Create Date: 2015-07-11 15:06:02.358534

"""

# revision identifiers, used by Alembic.
revision = '1c28d4dbb62'
down_revision = '7847a1b6d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
