"""add role assignment upon user creation

Revision ID: 3894a2c792a
Revises: 436381a0f76
Create Date: 2015-06-23 09:20:50.184148

"""

# revision identifiers, used by Alembic.
revision = '3894a2c792a'
down_revision = '436381a0f76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
