"""initial migration

Revision ID: 3d24da5066a
Revises: None
Create Date: 2015-06-11 10:04:07.155871

"""

# revision identifiers, used by Alembic.
revision = '3d24da5066a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
