"""typo correction

Revision ID: 47e5b122fac
Revises: 548cb418851
Create Date: 2015-07-04 20:21:51.331340

"""

# revision identifiers, used by Alembic.
revision = '47e5b122fac'
down_revision = '548cb418851'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
