"""added html posts

Revision ID: 548cb418851
Revises: 3815653e726
Create Date: 2015-07-04 19:22:20.566104

"""

# revision identifiers, used by Alembic.
revision = '548cb418851'
down_revision = '3815653e726'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
