"""additional comment stuff

Revision ID: 7847a1b6d3
Revises: 145ef3e6333
Create Date: 2015-07-09 08:38:49.014793

"""

# revision identifiers, used by Alembic.
revision = '7847a1b6d3'
down_revision = '145ef3e6333'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
